preDebug: true
services:
  - type: web
    name: heart-lab-ai
    env: node
    plan: free
    buildCommand: |
      echo "Current directory: $(pwd)"
      npm install
      npm run build
      echo "Build directory contents:"
      ls -la
      echo ".next directory contents:"
      ls -la .next || echo "No .next directory"
    startCommand: |
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo ".next directory contents:"
      ls -la .next || echo "No .next directory"
      npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    buildFilter:
      paths:
        - package.json
        - next.config.js
        - src/**
    nodeVersion: 18.17.0
    persistentStorage:
      mountPath: /opt/render/project/src/.next