services:
  - type: web
    name: heart-lab-ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    nodeVersion: 18.17.0