services:
  - type: web
    name: heart-lab-ai
    env: node
    plan: free
    buildCommand: |
      npm ci
      npm run build
      pwd
      ls -la
      ls -la .next || true
    startCommand: |
      ls -la
      npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    nodeVersion: 18.17.0
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - next.config.js
        - jsconfig.json
        - postcss.config.js
        - tailwind.config.js