services:
  - type: web
    name: heart-lab-ai
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      ls -la
      cd /opt/render/project/src
      ls -la
      npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    nodeVersion: 18.17.0
