services:
  - type: web
    name: heart-lab-ai
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: |
      npm ci
      npm run build
    startCommand: |
      ls -la
      ls -la .next
      npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    nodeVersion: 18.17.0