services:
  - type: web
    name: heart-lab-ai
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: heart-lab-ai-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true