services:
  - type: web
    name: heart-lab-ai
    env: node
    plan: free
    buildCommand: |
      npm ci
      NODE_ENV=production npm run build
      ls -la
      echo "Build completed"
    startCommand: |
      NODE_ENV=production npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    healthCheckPath: /
    nodeVersion: 18.17.0